language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo
matrix:
  allow_failures:
    - nightly
before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  - cd ..
script:
  - cargo test --all-features
